finance_app/urls.py
from django.contrib import admin
from django.urls import path, include

from finance_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('', include('tracker.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

tracker/urls.py
from django.urls import path
from .views import (
    IndexView,
    TransactionsListView,
    TransactionCreateView,
    TransactionUpdateView,
    TransactionDeleteView,
    TransactionsGetView,
    TransactionChartsView,
    TransactionExportView,
    TransactionImportView
)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('transactions/', TransactionsListView.as_view(), name='transactions-list'),
    path('transactions/charts/', TransactionChartsView.as_view(), name='transactions-charts'),
    path('transactions/create/', TransactionCreateView.as_view(), name='create-transaction'),
    path('transactions/<int:pk>/update/', TransactionUpdateView.as_view(), name='update-transaction'),
    path('transactions/<int:pk>/delete/', TransactionDeleteView.as_view(), name='delete-transaction'),

    path('get-transactions/', TransactionsGetView.as_view(), name='get-transactions'),

    path('transactions/export/', TransactionExportView.as_view(), name='export'),
    path('transactions/import/', TransactionImportView.as_view(), name='import'),

]

tracker/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import TransactionQuerySet


class User(AbstractUser):
    pass


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Transaction(models.Model):
    TRANSACTION_TYPE_CHOICES = (
        ('income', 'Income'),
        ('expense', 'Expense'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    type = models.CharField(max_length=7, choices=TRANSACTION_TYPE_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField()

    objects = TransactionQuerySet.as_manager()

    def __str__(self):
        date_aware = timezone.localtime(self.date)
        date_formatted = date_aware.strftime('%Y-%m-%d %H:%M:%S')
        return f"{self.type} of {self.amount} on {date_formatted} by {self.user.username}"

    class Meta:
        ordering = ['-date']

templates/partials/charts-container.html
{% load widget_tweaks %}

<div class="flex flex-col-reverse md:grid md:grid-cols-4 md:gap-4"
     id="charts-container">

    <div class="col-span-3">
        {{ income_expense_barchart|safe }}
        <span id="spinner" class="loading loading-dots loading-lg htmx-indicator block mx-auto"></span>

        <div class="grid grid-cols-2">
            {{ category_income_pie|safe }}
            {{ category_expense_pie|safe }}
        </div>
    </div>

    <div class="col-span-1 mt-4">
        <form hx-get="{% url 'transactions-charts' %}"
              hx-target="#charts-container"
              hx-swap="outerHTML"
              hx-indicator="#spinner"
              id="filterform">
            <div class="mb-2 form-control">
                {{ filter.form.transaction_type|add_label_class:"label text-white" }}
                {% render_field filter.form.transaction_type class="select bg-gray-50 text-gray-900" %}
            </div>

            <div class="mb-4 form-control">
                {% render_field filter.form.category class="text-green-500 border-gray-300 rounded focus:ring-green-500" %}
            </div>

            <div class="mb-2 form-control">
                {{ filter.form.start_date|add_label_class:"label text-white" }}
                {% render_field filter.form.start_date class="input bg-gray-50 text-gray-900" %}
            </div>

            <div class="mb-2 form-control">
                {{ filter.form.end_date|add_label_class:"label text-white" }}
                {% render_field filter.form.end_date class="input bg-gray-50 text-gray-900" %}
            </div>


            <button class="btn btn-success">
                Filter
            </button>
        </form>
    </div>


</div>

templates/partials/create-transaction.html
{% load widget_tweaks %}

<form hx-post="{% url 'create-transaction' %}">
    <h1 class="prose prose-2xl text-white">
        Create Transaction
    </h1>

    {% include 'partials/transaction-form.html' %}

    <div class="flex">
        <button class="btn btn-success mr-2">Add</button>
        <form method="dialog">
            <button class="btn btn-error">Cancel</button>
        </form>
    </div>


</form>

templates/partials/import-transaction.html
{% load widget_tweaks %}

<h1 class="mb-2 prose prose-2xl text-white">
    Import Transactions
</h1>

<form hx-encoding="multipart/form-data" hx-post="{% url 'import' %}">

    <div class="mb-4">
        <input type="file" name="file" class="file-input max-w-xs"
               accept=".csv">
    </div>

    <div class="flex">
        <button class="btn btn-success mr-2">Upload</button>
        <form method="dialog">
            <button class="btn btn-error">Cancel</button>
        </form>
    </div>
</form>

templates/partials/navbar.html
<nav class="navbar bg-base-100 fixed">
  <div class="navbar-start">
    <a href="{% url 'index' %}" class="btn btn-ghost text-xl">Finance Tracker</a>
  </div>
  <div class="navbar-end">
    <div class="dropdown dropdown-end md:hidden" id="mobile-menu-dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost" id="mobile-menu-button">
        {% heroicon_outline "bars-3" %}
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
          {% if user.is_authenticated %}
          <li><a href="{% url 'transactions-list' %}" aria-current="page">My Transactions</a></li>
          <li><a href="{% url 'transactions-charts' %}" aria-current="page">My Charts</a></li>
          <li><a href="{% url 'account_logout' %}" aria-current="page">Logout</a></li>
          {% else %}
          <li><a href="{% url 'account_login' %}" aria-current="page">Login</a></li>
          <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
          {% endif %}
      </ul>
    </div>
    <ul class="menu menu-horizontal px-1 hidden md:flex">
        {% if user.is_authenticated %}
        <li><a href="{% url 'transactions-list' %}" aria-current="page">My Transactions</a></li>
        <li><a href="{% url 'transactions-charts' %}" aria-current="page">My Charts</a></li>
        <li><a href="{% url 'account_logout' %}" aria-current="page">Logout</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}" aria-current="page">Login</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
    </ul>
  </div>
</nav>

templates/partials/transaction-form.html
{% load widget_tweaks %}

<div class="mb-2 form-control text-black">
    {{ form.type|add_label_class:"label text-white" }}
    {% render_field form.type class="input bg-gray-50" %}
</div>
<div class="mb-2 form-control">
    {{ form.amount|add_label_class:"label text-white" }}
    {% render_field form.amount class="input text-black bg-gray-50" %}

    {% for error in form.amount.errors %}
    <p class="text-red-400 mt-1">{{ error }}</p>
    {% endfor %}
</div>
<div class="mb-2 form-control">
    {{ form.date|add_label_class:"label text-white" }}
    {% render_field form.date class="input text-black bg-gray-50" %}
</div>
<div class="mb-2 form-control">
    {{ form.category|add_label_class:"label text-white" }}
    {% render_field form.category class="text-green-500 border-gray-300 rounded focus:ring-green-500" %}
</div>

templates/partials/transaction-success.html
<div role="alert" class="alert alert-success">
    <span>{{ message }}</span>
</div>

<div class="mt-4">
    <button class="btn btn-info"
            hx-get="{% url 'create-transaction' %}"
            hx-target="#form-modal"
            hx-trigger="click"
            onclick="crud_modal.showModal()">
        Add Transaction
    </button>

    <button class="btn btn-success"
            hx-get="{% url 'transactions-list' %}"
            hx-push-url="true"
            hx-target="#transaction-block">
        View transactions
    </button>
</div>

templates/partials/transactions-container.html
{% load widget_tweaks %}
{% load partials %}
{% load humanize %}

<div class="flex flex-col-reverse md:grid md:grid-cols-4 md:gap-4"
     id="transaction-container">

    <div class="col-span-3">
        <div class="mt-4">
            <h1 class="mt-4 mb-4 prose prose-2xl text-white">
                Totals
            </h1>

            <table class="table">
                <thead class="text-xs text-white uppercase">
                <tr class="border-gray-300">
                    <th>Total Income</th>
                    <th>Total Expenses</th>
                    <th>Net Income</th>
                </tr>
                </thead>
                <tbody>
                <tr class="border-gray-300">
                    <td>{{ total_income|intcomma }}</td>
                    <td>{{ total_expenses|intcomma }}</td>
                    <td>{{ net_income|intcomma }}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="flex justify-between items-center mt-4 mb-6">
            <h1 class="mt-8 mb-4 prose prose-2xl text-white">
                Transactions
            </h1>

            <div class="flex items-center">

                <a hx-get="{% url 'create-transaction' %}"
                   hx-target="#form-modal"
                   hx-trigger="click"
                   onclick="crud_modal.showModal()"
                   title="Add Transaction"
                   class="cursor-pointer mr-2">

                    {% heroicon_outline "plus-circle" class="w-10 h-10" fill="green" %}

                </a>

                <a hx-get="{% url 'export' %}"
                   hx-include="#filterform"
                   title="Export Transactions"
                   class="cursor-pointer mr-2">

                    {% heroicon_outline "arrow-down-tray" class="w-10 h-10" %}
                </a>

                <a hx-get="{% url 'import' %}"
                   hx-target="#form-modal"
                   hx-trigger="click"
                   onclick="crud_modal.showModal()"
                   title="Import Transactions"
                   class="cursor-pointer mr-2">

                    {% heroicon_outline "arrow-up-tray" class="w-10 h-10" %}
                </a>

            </div>
        </div>
        {% if transactions %}

        <table class="table">
            <thead class="text-xs text-white uppercase">
            <tr class="border-gray-300">
                <th class="px-6 py-3">Date</th>
                <th class="px-6 py-3">Category</th>
                <th class="px-6 py-3">Type</th>
                <th class="px-6 py-3">Amount</th>
                <th></th>
            </tr>
            </thead>

            <tbody>
            {% partialdef transaction_list inline=True %}
            {% for transaction in transactions %}
            {% if forloop.last and transactions.has_next %}
            <tr class="border-gray-300"
                hx-get="{% url 'get-transactions' %}?page={{ transactions.next_page_number }}"
                hx-trigger="revealed"
                hx-swap="afterend"
                hx-include="#filterform"
                hx-indicator="#spinner">

                {% else %}
            <tr class="border-gray-300">
                {% endif %}
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.category }}</td>
                <td>{{ transaction.type }}</td>
                <td>{{ transaction.amount|intcomma }}</td>
                <td class="flex items-center">
                    <a hx-get="{% url 'update-transaction' transaction.pk %}"
                       hx-target="#form-modal"
                       hx-trigger="click"
                       onclick="crud_modal.showModal()"
                       title="Update Transaction"
                       class="cursor-pointer">
                        {% heroicon_outline "pencil-square" class="mr-1" %}
                    </a>
                    <a hx-delete="{% url 'delete-transaction' transaction.pk %}"
                       hx-target="#form-modal"
                       hx-trigger="click"
                       onclick="crud_modal.showModal()"
                       hx-confirm="Are you sure you want to delete this transaction?"
                       title="Delete Transaction"
                       class="cursor-pointer"
                    >{% heroicon_outline "x-circle" %}</a>

                </td>
            </tr>
            {% endfor %}
            {% endpartialdef %}
            </tbody>
        </table>
        <span id="spinner" class="loading loading-dots loading-lg htmx-indicator block mx-auto"></span>

        {% else %}

        <p class="text-2xl text-white">
            No transactions found
        </p>

        {% endif %}
    </div>

    <div class="col-span-1 mt-4">
        <form hx-get="{% url 'transactions-list' %}"
              hx-target="#transaction-container"
              hx-swap="outerHTML"
              id="filterform">
            <div class="mb-2 form-control">
                {{ filter.form.transaction_type|add_label_class:"label text-white" }}
                {% render_field filter.form.transaction_type class="select bg-gray-50 text-gray-900" %}
            </div>

            <div class="mb-4 form-control">
                {% render_field filter.form.category class="text-green-500 border-gray-300 rounded focus:ring-green-500" %}
            </div>

            <div class="mb-2 form-control">
                {{ filter.form.start_date|add_label_class:"label text-white" }}
                {% render_field filter.form.start_date class="input bg-gray-50 text-gray-900" %}
            </div>

            <div class="mb-2 form-control">
                {{ filter.form.end_date|add_label_class:"label text-white" }}
                {% render_field filter.form.end_date class="input bg-gray-50 text-gray-900" %}
            </div>


            <button class="btn btn-success">
                Filter
            </button>
        </form>
    </div>


</div>

<dialog id="crud_modal" class="modal">
  <div class="modal-box" id="form-modal">
    <div class="modal-action">
      <form method="dialog">
      </form>
    </div>
  </div>
</dialog>

templates/partials/update-transaction.html
{% load widget_tweaks %}

<h1 class="prose prose-2xl text-white">
    Update Transaction
</h1>

<form hx-post="{% url 'update-transaction' transaction.pk %}">

    {% include 'partials/transaction-form.html' %}

    <div class="flex">
        <button class="btn btn-success mr-2">Update</button>
        <form method="dialog">
            <button class="btn btn-error">Cancel</button>
        </form>
    </div>

</form>